---
- hosts: main
  become: yes

  tasks:
    - name: Install Baseline Configuration
      import_tasks: tasks/baseline.yml
      tags: baseline_install

- hosts: nfs
  become: yes

  tasks:
    - name: Mount NFS Drives
      import_tasks: tasks/nfs.yml
      tags: nfs_install

- hosts: docker
  become: yes

  tasks:
    - name: Install Docker
      import_tasks: tasks/docker.yml
      tags: docker_install
    
    - name: Deploy mariadb
      import_tasks: tasks/mariadb.yml
      tags: mariadb_install

    - name: "Deploy Traefik"
      import_tasks: tasks/traefik.yml
      tags: traefik_install
    
    - name: "Deploy Portainer"
      import_tasks: tasks/portainer.yml
      tags: portainer_install
    
    - name: "Deploy homepage"
      import_tasks: tasks/homepage.yml
      tags: homepage_install

    - name: Deploy dozzle
      import_tasks: tasks/dozzle.yml
      tags: dozzle_install

    - name: Deploy Invoiceninja
      import_tasks: tasks/invoiceninja.yml
      tags: invoiceninja_install

    - name: Deploy Jackett
      import_tasks: tasks/jackett.yml
      tags: jackett_install
    
    - name: Deploy Mealie
      import_tasks: tasks/mealie.yml
      tags: mealie_install 

    - name: Deploy sabnzb
      import_tasks: tasks/sabnzbd.yml
      tags: sabnzb_install
    
    - name: Deploy Sonarr
      import_tasks: tasks/sonarr.yml
      tags: sonarr_install

    - name: Deploy Radarr
      import_tasks: tasks/radarr.yml
      tags: radarr_install

    - name: Deploy Readarr
      import_tasks: tasks/readarr.yml
      tags: readarr_install

    - name: Deploy Prowlarr
      import_tasks: tasks/prowlarr.yml
      tags: prowlarr_install

    - name: Deploy Lidarr
      import_tasks: tasks/lidarr.yml
      tags: lidarr_install

    - name: Deploy Jellyseerr
      import_tasks: tasks/jellyseerr.yml
      tags: jellyseerr_install

    - name: Deploy speedtest
      import_tasks: tasks/speedtest.yml
      tags: speedtest_install

    - name: Deploy pykms
      import_tasks: tasks/pykms.yml
      tags: pykms_install
       
    - name: Deploy qbitorrent
      import_tasks: tasks/qbittorrent.yml
      tags: qbittorrent_install   
    
    - name: Deploy vaultwarden
      import_tasks: tasks/vaultwarden.yml
      tags: vaultwarden_install

    - name: Deploy planka
      import_tasks: tasks/planka.yml
      tags: planka_install

    - name: Deploy osTicket
      import_tasks: tasks/osticket.yml
      tags: osticket_install

    - name: Deploy homeassistant
      import_tasks: tasks/homeassistant.yml
      tags: homeassistant_install
    
    - name: Deploy Watchtower
      import_tasks: tasks/watchtower.yml
      tags: watchtower_install

    - name: Deploy Homarr
      import_tasks: tasks/homarr.yml
      tags: homarr_install

    - name: Deploy Dashdot
      import_tasks: tasks/dashdot.yml
      tags: dashdot_install
    
    - name: Deploy Plex
      import_tasks: tasks/plex.yml
      tags: plex_install

- hosts: omada
  become: yes

  tasks: 
    - name: Install Docker
      import_tasks: tasks/docker.yml
      tags: docker_install

    - name: Deploy Omada
      import_tasks: tasks/omada.yml
      tags: omada_install
    
    - name: Deploy Watchtower
      import_tasks: tasks/watchtower.yml
      tags: watchtower_install
    