---
- name: Set Facts
  set_fact:
    container_name: 'dashdot'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_configs }}/{{container_name}}"
    - "{{ docker_configs }}/{{container_name}}/config"
  
- name: Create the {{container_name}} container
  docker_container:
    name: dash
    image: mauricenino/dashdot:latest
    privileged: yes
    restart_policy: always
    recreate: true
    networks:
      - name: traefik
    volumes:
      - /:/mnt/host:ro
    labels:
      traefik.enable=true
      traefik.http.routers.{{container_name}}.rule=Host(`{{container_name}}.{{traefik_domain}}`)
      traefik.http.routers.{{container_name}}.entrypoints=https
      traefik.http.routers.{{container_name}}.tls.certresolver=cloudflare
