---
- name: Set Facts
  set_fact:
    container_name: 'homeassistant'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_configs }}/{{container_name}}"
    - "{{ docker_configs }}/{{container_name}}/config"
  
- name: Create the {{container_name}} container
  docker_container:
    name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:latest
    restart_policy: always
    recreate: true
    networks:
      - name: traefik
    ports:
      - 8123
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
      AUTO_UPDATE: "true" #optional
    volumes:
      - /mnt/nfs/docker/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable=true
      traefik.http.services.{{container_name}}.loadbalancer.server.port=8123
      traefik.http.services.{{container_name}}.loadbalancer.server.scheme=http
      traefik.http.routers.{{container_name}}.rule=Host(`{{container_name}}.{{traefik_domain}}`)
      traefik.http.routers.{{container_name}}.entrypoints=https
      traefik.http.routers.{{container_name}}.tls.certresolver=cloudflare