---
- name: Set Facts
  set_fact:
    container_name: 'invoiceninja'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_configs }}/{{container_name}}"
    - "{{ docker_configs }}/{{container_name}}/config"

- name: Generate Environment variables
  template:
    src: templates/{{container_name}}-stack.env
    dest: "{{ docker_configs }}/{{container_name}}/stack.env"
  notify: start docker

- name: Render docker-compose config
  template:
    src: templates/{{container_name}}-docker-compose.yml
    dest: "{{ docker_configs }}/{{container_name}}/docker-compose.yml"
  notify: start docker
