---
- name: Mount an NFS volume - docker configs
  ansible.posix.mount:
    src: truenas.comprofix.xyz:/mnt/DS4232/docker
    path: /mnt/nfs/docker
    opts: rw,sync,hard
    state: mounted
    fstype: nfs

- name: Mount an NFS volume - data
  ansible.posix.mount:
    src: truenas.comprofix.xyz:/mnt/DS4232/data
    path: /mnt/nfs/data/
    opts: rw,sync,hard
    state: mounted
    fstype: nfs