---
- name: Set Facts
  set_fact:
    container_name: 'omada'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_configs }}/{{container_name}}"
    - "{{ docker_configs }}/{{container_name}}/config"
  
- name: Create the {{container_name}} container
  docker_container:
    name: omada
    image: mbentley/omada-controller:latest
    restart_policy: always
    recreate: true
    network_mode: host
    env:
      PUID: "508"
      PGID: "508"
      MANAGE_HTTP_PORT: "8088"
      MANAGE_HTTPS_PORT: "8043"
      PORTAL_HTTP_PORT: "8088"
      PORTAL_HTTPS_PORT: "8843"
      PORT_APP_DISCOVERY: "27001"
      PORT_ADOPT_V1: "29812"
      PORT_UPGRADE_V1: "29813"
      PORT_MANAGER_V1: "29811"
      PORT_MANAGER_V2: "29814"
      PORT_DISCOVERY: "29810"
      SHOW_SERVER_LOGS: "true"
      SHOW_MONGODB_LOGS: "false"
      TZ: "Australia/Brisbane"
    volumes:
      - /omada/data:/opt/tplink/EAPController/data
      - /omada/logs:/opt/tplink/EAPController/logs
    labels:
      traefik.enable=true
      traefik.http.routers.{{container_name}}.rule=Host(`{{container_name}}.{{traefik_domain}}`)
      traefik.http.routers.{{container_name}}.entrypoints=https
      traefik.http.routers.{{container_name}}.tls.certresolver=cloudflare