---
- name: Set Facts
  set_fact:
    container_name: 'portainer'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_configs }}/{{container_name}}"
    - "{{ docker_configs }}/{{container_name}}/config"
  
- name: Create the {{container_name}} container
  docker_container:
    name: portainer
    image: portainer/portainer
    restart_policy: always
    recreate: true
    networks:
      - name: traefik
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
      AUTO_UPDATE: "true" #optional
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/nfs/docker/portainer/data:/data
    labels:
      traefik.enable=true
      traefik.http.services.{{container_name}}.loadbalancer.server.port=9443
      traefik.http.services.{{container_name}}.loadbalancer.server.scheme=https
      traefik.http.routers.{{container_name}}.rule=Host(`{{container_name}}.{{traefik_domain}}`)
      traefik.http.routers.{{container_name}}.entrypoints=https
      traefik.http.routers.{{container_name}}.tls.certresolver=cloudflare