---
- name: Set Facts
  set_fact:
    container_name: 'vaultwarden'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_configs }}/{{container_name}}"
    - "{{ docker_configs }}/{{container_name}}/config"
  
- name: Create the {{container_name}} container
  docker_container:
    name: vaultwarden
    image: vaultwarden/server:latest
    restart_policy: always
    recreate: true
    networks:
      - name: traefik
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
    volumes:
      /mnt/nfs/docker/vaultwarden/data:/data
    labels:
      traefik.enable=true
      traefik.http.routers.{{container_name}}.rule=Host(`vault.comprofix.com`)
      traefik.http.routers.{{container_name}}.entrypoints=https
      traefik.http.routers.{{container_name}}.tls.certresolver=cloudflare
