---
version: '3.7'
services:
  server:
    container_name: invoiceninja-nginx
    image: nginx
    env_file: stack.env
    restart: always
    volumes:
      - /mnt/nfs/docker/invoiceninja/config/nginx/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf
      - /mnt/nfs/docker/invoiceninja/docker/app/public:/var/www/app/public
      - /mnt/nfs/docker/invoiceninja/docker/app/storage:/var/www/app/storage
    depends_on:
      - app
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{{container_name}}.rule=Host(`invoice.comprofix.com`)"
      - "traefik.http.routers.{{container_name}}.entrypoints=https"
      - "traefik.http.routers.{{container_name}}.tls.certresolver=cloudflare"

  app:
    container_name: invoiceninja-app
    image: invoiceninja/invoiceninja:5
    env_file: stack.env
    restart: always
    volumes:
      - /mnt/nfs/docker/invoiceninja/config/hosts:/etc/hosts
      - /mnt/nfs/docker/invoiceninja/docker/app/public:/var/www/app/public
      - /mnt/nfs/docker/invoiceninja/docker/pp/storage:/var/www/app/storage
    networks:
      - traefik

networks:
  traefik:
    external: true