---
version: "3"
services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb:10.6.13
    container_name: mariadb
    environment:
      - PUID=0
      - PGID=0
      - MYSQL_ROOT_PASSWORD=8ug58unny
      - TZ=Australia/Brisbane
    volumes:
      - /mnt/nfs/docker/mariadb/config:/config
    restart: unless-stopped
    ports:
      - 3306:3306