---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:radarr
    volumes:
      - /mnt/nfs/docker/radarr/config:/config
      - /mnt/nfs/data/movies:/movies #optional
      - /mnt/nfs/data/downloads:/downloads #optional
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{{container_name}}.rule=Host(`{{container_name}}.{{traefik_domain}}`)"
      - "traefik.http.routers.{{container_name}}.entrypoints=https"
      - "traefik.http.routers.{{container_name}}.tls.certresolver=cloudflare"

networks:
  traefik:
    external: true