---
version: "2.1"
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
    volumes:
      - /dockerdata/readarr/config:/config
      - /mnt/nfs/data/ebooks:/books #optional
      - /mnt/nfs/data/downloads/:/downloads #optional
    restart: unless-stopped
    networks:
      - traefik

networks:
  traefik:
    external: true