---
version: "2.1"
services:
  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
      - hostname=sabnzbd.comprofix.xyz
    volumes:
      - /mnt/nfs/docker/sabnzbd/config:/config
      - /mnt/nfs/data/downloads:/downloads

    restart: always
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{{container_name}}.rule=Host(`{{container_name}}.{{traefik_domain}}`)"
      - "traefik.http.routers.{{container_name}}.entrypoints=https"
      - "traefik.http.routers.{{container_name}}.tls.certresolver=cloudflare"

networks:
  traefik:
    external: true