---
# {{ ansible_managed }}
version: '3'

services:
  traefik:
    image: traefik:{{ traefik_version }}
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik
    environment:
      - CF_API_EMAIL={{ CF_API_EMAIL }}
      - CF_DNS_API_TOKEN={{ CF_DNS_API_TOKEN }}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.{{ traefik_domain }}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=cloudflare"
{% for key in traefik_wildcards %}
{% set index = loop.index - 1 %}
      - "traefik.http.routers.dashboard.tls.domains[{{ index }}].main={{ key }}"
      - "traefik.http.routers.dashboard.tls.domains[{{ index }}].sans=*.{{ key }}"
{% endfor %}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ docker_configs }}/{{container_name}}/config/traefik.yml:/traefik.yml"
      - "{{ docker_configs }}/{{container_name}}/config/config.yml:/config.yml"
      - "{{ docker_configs }}/{{container_name}}/config/acme.json:/acme.json"

    container_name: traefik

networks:
  traefik:
    external: true



